//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Departments = new HashSet<Department>();
        }
    
        public int employee_id { get; set; }

        [StringLength(50)]
        [Required(ErrorMessage = "This field is required")]
        public string employee_name { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public int role_id { get; set; }
        
        [Required(ErrorMessage = "This field is required")]
        public long salary { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string address { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "This field is required")]
        public System.DateTime joining_date { get; set; }

        //[StringLength(13, MinimumLength = 13)]
        [Range(1000000000000, 9999999999999, ErrorMessage = "Account No must be 13 digits long")]
        [Required(ErrorMessage = "This field is required")]
        public long account_no { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public int bank_id { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Role Role { get; set; }
    }
}
